"""empty message

Revision ID: 1ad3c3c41833
Revises: 226218403d05
Create Date: 2013-10-20 17:06:35.064580

"""

# revision identifiers, used by Alembic.
revision = '1ad3c3c41833'
down_revision = '226218403d05'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column('points', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action', 'points')
    ### end Alembic commands ###
