"""empty message

Revision ID: 226218403d05
Revises: 3b8d0d9b8435
Create Date: 2013-10-20 03:59:04.275814

"""

# revision identifiers, used by Alembic.
revision = '226218403d05'
down_revision = '3b8d0d9b8435'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('added', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('due', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('finish_time', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table(u'event')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'event',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'text', sa.TEXT(), nullable=True),
    sa.Column(u'added', sa.DATETIME(), nullable=True),
    sa.Column(u'modified', sa.DATETIME(), nullable=True),
    sa.Column(u'due', sa.DATETIME(), nullable=True),
    sa.Column(u'start_time', sa.DATETIME(), nullable=True),
    sa.Column(u'finish_time', sa.DATETIME(), nullable=True),
    sa.Column(u'priority', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.drop_table('action')
    ### end Alembic commands ###
