"""empty message

Revision ID: 3b8d0d9b8435
Revises: None
Create Date: 2013-10-20 03:40:44.491716

"""

# revision identifiers, used by Alembic.
revision = '3b8d0d9b8435'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
