#! /usr/bin/env python

print """Content-type: text/html

<html><head><title>Add Nugget</title></head>
<body>
<form method="post" action="add_confirm">
username:
</br>
<textarea name="user" cols="60" rows="1"></textarea>
<br/>
url:
</br>
<textarea name="url" cols="60" rows="1"></textarea>
<br/>
description:
<br/>
<textarea name="description" cols="60" rows="20"></textarea>
<br/>
<input type="submit" value="Add">
</form>
</body></html>
"""
