#! /usr/bin/env python

import cgi
import sys
sys.path.append('..')
from hactar.core import User
from hactar.sqlite import Sqlite
form = cgi.FieldStorage()

user = form.getvalue('user')

def head():
    print "Content-type: text/html"
    print
    print "<html><head><title>Create User Confirm</title></head>"

def body(form):
    print "<body>"
    print "New user %s created.</br>" % form.getvalue('user')
    print "</body>"

def foot():
    print "</html>"

def already_exists(user):
    print "<body>"
    print 'Failed: user %s already exists.' % user
    print "</body>"

head()
# validate user
try:

    usr = Sqlite(user+'.sqlite')
except ValueError:
    # display invalid user page
    already_exists(user)
else:
    body(form)

foot()
