#! /usr/bin/env python

import cgi
import sys
sys.path.append('..')
from hactar.core import User

form = cgi.FieldStorage()

user = form.getvalue('user')
terms = form.getvalue('terms')

def head():
    lines = [
    "Content-type: text/html",
    "",
    "<html><head><title>View Nuggets</title></head>",
    "<body>",
    ]
    return '\n'.join(lines)
def foot():
    return "</body></html>"

def body(ngts):
    lines = ['You are viewing user %s and terms: %s</br>' % (user, terms)]
    add = lines.append
    if len(ngts) == 0:
        add('No results were found')
    else:
        add('<table border=0>')
        add('<tr>')
        for col in ['URI', 'Description', 'Added', 'Modified']:
            add('<td>%s</td>' % col)
        add('</tr>')
        for ngt in ngts:
            add('<tr>')
            add(cell('<a href=%s>%s' % (ngt[2], ngt[2])))
            add(cell(ngt[5]))
            add(cell(ngt[0]))
            add(cell(ngt[1]))
            add('</tr>')
            
        add('</table>')
    return ''.join(lines)

def cell(contents):
    return '<td>%s</td>' % contents

def unknown_user(user):
    return 'User %s is unknown' % user

print head()
try:
    usr = User(user)
except ValueError:
    print unknown_user(user)
else:
    ngts = usr.get_nuggets(terms.split() if terms is not None else None)
    print body(ngts)
print foot()
