#! /usr/bin/env python

import cgi
import sys
sys.path.append('..')
from hactar.core import User

form = cgi.FieldStorage()

user = form.getvalue('user')
terms = form.getvalue('terms')

def head():
    lines = [
    "Content-type: text/html",
    "",
    "<html><head><title>View Nuggets</title></head>",
    "<body>",
    ]
    return '\n'.join(lines)
def foot():
    return "</body></html>"

def body(ngts):
    lines = ['You are viewing user %s and terms: %s' % (user, terms)]
    if len(ngts) == 0:
        lines.append('No results were found')
    else:
        for ngt in ngts:
            lines.append(str(ngt))
    return  '</br>'.join(lines)
def unknown_user(user):
    return 'User %s is unknown' % user

print head()
try:
    usr = User(user)
except ValueError:
    print unknown_user(user)
else:
    ngts = usr.get_nuggets(terms.split() if terms is not None else None)
    print body(ngts)
print foot()
